db_type: YamlVec
a_sabr: "../host.rc"

peer_list:
  - uuid: "1"
    name: Instance 1
    endpoints:
      - "tcp 127.0.0.1:6500"
      - "udp 127.0.0.1:6550"
    color: MAGENTA

  - uuid: "2"
    name: Instance 2
    endpoints:
      - "tcp 127.0.0.1:7500"
      - "udp 127.0.0.1:7550"
    color: BLUE

  - uuid: "3"
    name: Instance 3
    endpoints:
      - "tcp 127.0.0.1:8000"
      - "udp 127.0.0.1:8050"
    color: ORANGE

room_list:
  - uuid: 1
    name: Default
    participants:
      - peer_uuid: "Instance 1"
        endpoint: "tcp 127.0.0.1:6500"
      - peer_uuid: "Instance 2"
        endpoint: "udp 127.0.0.1:7550"
      - peer_uuid: "Instance 3"
        endpoint: "tcp 127.0.0.1:8000"
